{% set name = "kim-edn" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e5cd30ef9c486c8a59ef77e78f966a01f7848361952ba1ff0290d256c5dbb572

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=80
    - setuptools-scm >=9.2
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - kim_edn
  commands:
    - pip check

about:
  home: https://github.com/openkim/kim-edn
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-EDN encoder and decoder for Python
  description: |
    KIM-EDN encoder and decoder embraces a subset of
    edn <https://openkim.org/doc/schema/edn-format> as a standard data
    format. The primary purpose of this data format choice is to serve as a
    notational superset to JSON with the enhancements being that it (1)
    allows for comments and (2) treats commas as whitespace enabling easier
    templating. KIM-EDN encoder and decoder works with Python 3.10 and later.
    It is pure Python code with no runtime dependencies.
  dev_url: https://github.com/openkim/kim-edn

extra:
  recipe-maintainers:
    - yafshar