{% set name = "kim-edn" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 04d1b26c8c0736729e003c57b86cb0993995d0d9971903d2de3df94126c0f09b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
    - versioneer >=0.29
  run:
    - python >=3.8

test:
  imports:
    - kim_edn

about:
  home: https://github.com/openkim/kim-edn
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: KIM-EDN encoder and decoder for Python
  description: |
    KIM-EDN encoder and decoder embraces a subset of
    edn <https://openkim.org/doc/schema/edn-format> as a standard data
    format. The primary purpose of this data format choice is to serve as a
    notational superset to JSON with the enhancements being that it (1)
    allows for comments and (2) treats commas as whitespace enabling easier
    templating. KIM-EDN encoder and decoder works for Python 3.6+. It is pure
    Python code with no dependencies.
  dev_url: https://github.com/openkim/kim-edn

extra:
  recipe-maintainers:
    - yafshar
