{% set name = "kim_edn" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 47aaf852cc8c2876be743c91d230de512d803e0be4c1d0e2b6aabc6a80552c9a

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - kim_edn

about:
  home: https://github.com/openkim/kim-edn
  license: CDDL-1.0
  license_family: OTHER
  license_file: LICENSE.CDDL
  summary: 'KIM-EDN encoder and decoder for Python'
  description: |
    KIM-EDN encoder and decoder embraces a subset of
    edn <https://openkim.org/doc/schema/edn-format> as a standard data
    format. The primary purpose of this data format choice is to serve as a
    notational superset to JSON with the enhancements being that it (1)
    allows for comments and (2) treats commas as whitespace enabling easier
    templating. KIM-EDN encoder and decoder works for Python 3.6+. It is pure
    Python code with no dependencies.
  dev_url: https://github.com/openkim/kim-edn

extra:
  recipe-maintainers:
    - yafshar
